@startuml

title 取消课程

actor 运营 as user
participant "运营平台" as bom
participant "供应商中心" as vc
participant "用户中心" as uc
participant "工作流" as wf
participant "消息中心" as mc
actor "供应商用户" as cpm

activate user
user -> bom: 课程取消请求
deactivate user

activate bom
bom -> bom: 参数校验/转换
bom -> vc: 课程id
deactivate bom

activate vc
vc -> vc: 查询该课程下所有的预约信息
note left of vc: 包含供应商id、课程预约id
vc --> bom: 返回数据
deactivate vc

activate bom
bom -> bom: 提取课程预约id集合
bom -> vc: 课程预约id集合与表名
deactivate bom

activate vc
vc -> vc: 检索工作流历史记录
vc --> bom: 返回数据
deactivate vc

activate bom
bom -> bom: 提取工作流实例id集合
bom -> wf: 批量取消工作流
activate wf
wf -> wf: 取消任务
wf --> bom: 操作结果
deactivate wf
bom -> bom: 提取businessId集合
bom -> vc: businessId集合
activate vc #DarkSalmon
vc -> vc: 批量更新工作流历史记录
vc --> bom: 操作结果
deactivate vc
bom -> bom: 提取供应商id集合
bom -> uc: 供应商id集合
deactivate bom

activate uc
uc -> uc: 查询关联的所有用户集合
uc --> bom: 返回数据
deactivate uc

activate bom
bom -> bom: 组装消息体
note right of bom: 供应商id与用户id对应
bom -> bom: 组装消息发送对象
bom -> mc: 请求批量推送站内信
activate mc #DarkSalmon
mc -> mc: 创建定时任务
mc --> bom: 创建成功
bom -> vc: 课程id
deactivate bom
activate vc
vc -> vc: 更新课程状态为已取消
vc --> bom: 操作结果
deactivate vc
activate bom
mc -> mc: 5分钟后触发定时任务
mc -> cpm: 开始推送站内信
deactivate mc

activate cpm
cpm -> cpm: 收到课程取消提醒
bom --> user: 取消课程成功
deactivate bom

@enduml