@startuml

title 自由品牌制造商登记

actor 用户 as User

participant "运营平台" as Partner
participant "工作流" as Workflow

activate User
User -> Partner: 查询供应商
deactivate User

activate Partner
Partner --> User: 返回供应商列表
deactivate

activate User
User -> User: 选择供应商
User -> User: 填写制造商基本信息
User -> Partner: 提交保存
deactivate

activate Partner
Partner -> Workflow: 提交审批
deactivate

activate Workflow
Workflow -> Workflow: 新增工厂
Workflow -> Workflow: 填写基本信息
Workflow -> Workflow: 审核分值及评语
Workflow -> Workflow: 资质评价
note right of Workflow : 必须添加一个合格工厂
Workflow --> User: 审批结果
deactivate

activate User
User -> User: 启用
@enduml
